[pytest]
log_level = DEBUG
log_file = pytest_log/aeroparts_order_test_log.txt
log_file_level = DEBUG
log_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_date_format = %d/%m/%Y %H:%M:%S

markers =
    criterium_1: Als bij een AOG-order de bestelling onder de ETA zit, wordt deze besteld
    criterium_2: Als bij een AOG-order de bestelling boven de ETA zit, wordt deze niet besteld
    criterium_3: Als bij een order met certificering geen onderdeel met certificering beschikbaar is, krijgt de gebruiker hier melding van
    criterium_4: Als bij een order met ETA geen onderdeel binnen de ETA beschikbaar is, krijgt de gebruiker hier melding van
    criterium_5: Als bij een order met vervaldatum geen onderdeel binnen de vervaldatum beschikbaar is, krijgt de gebruiker hier melding van
    criterium_6: Als bij een order voor een vliegtuig geen onderdeel voor dat vliegtuig beschikbaar is, krijgt de gebruiker hier melding van
    criterium_7: Als een order zonder problemen kan worden uitgevoerd, krijgt de gebruiker geen errormelding
    criterium_8: Als een order certificering nodig heeft en er is er een met certificering beschikbaar, dan wordt er een onderdeel met certificering besteld
    criterium_9: Als een order certificering nodig heeft en er is er geen met certificering beschikbaar, dan wordt er niks besteld
    criterium_10: Als een order een vervaldatum heeft, wordt er een onderdeel binnen de vervaldatum, of niks, besteld
    criterium_11: Als een order niet door een warehouse kan worden vervuld, worden de verschillende goedgekeurde leveranciers met hun prijzen getoond.
    criterium_12: Als een part uit een warehouse wordt gehaald, dan wordt de stock van dit item met de gevraagde hoeveelheid verlaagd bij dit warehouse.
    criterium_13: Wanneer een item met AOG-prioriteit wordt besteld, dan wordt alleen besteld wanneer het onderdeel binnen een uur leverbaar is
    criterium_14: Wanneer een item met urgent-prioriteit wordt besteld, dan wordt alleen besteld wanneer het onderdeel binnen vijf dagen leverbaar is
    criterium_15: Wanneer een item met routine-prioriteit wordt besteld, dan kan een part worden besteld dat niet binnen 5 dagen leverbaar is
    criterium_16: Wanneer een negatief aantal parts wordt besteld, runt het script niet
    criterium_17: Wanneer een niet-geheel aantal parts wordt besteld, runt het script niet
    criterium_18: Wanneer een geheel, niet-negatief aantal parts wordt besteld, runt het script wel
    criterium_19: Wanneer het gevraagde part van een order niet overeenkomt met het gevraagde vliegtuigtype, runt het script niet
    criterium_20: Wanneer het gevraagde part van een order overeenkomt met het gevraagde vliegtuigtype, runt het script
    criterium_21: Wanneer een part in USD wordt besteld, wordt de prijs correct naar EUR converteerd
    criterium_22: Wanneer een part in EUR wordt besteld, wordt de prijs niet geconverteerd
    criterium_23: Als veel items in dezelfde seconde worden besteld, hebben ze ieder een uniek ordernummer
    criterium_24: De kosten van een part uit de warehouse wordt met 3 decimalen na de komma (of zoveel als relevant) weergegeven
    criterium_25: De kosten van een part van een supplier wordt met 3 decimalen na de komma weergegeven
    method_calculate_total_cost_eur
    method_deduct_stock
    method_generate_order_id
    method_place_order
    method_select_supplier
    method_select_warehouse
    method_to_eur
    method_validate_request
