[pytest]
markers =
    criterium_1
    criterium_2
    criterium_3
    criterium_4
    criterium_5
    criterium_6
    criterium_7
    criterium_8
    criterium_9
    criterium_10
    criterium_11
    criterium_12
    criterium_13
    criterium_14
    criterium_15
    criterium_16
    criterium_17
    criterium_18
    criterium_19
    criterium_20
    criterium_21
    criterium_22
    criterium_23
    criterium_24
    criterium_25
    method_calculate_total_cost_eur
    method_deduct_stock
    method_generate_order_id
    method_place_order
    method_select_supplier
    method_select_warehouse
    method_to_eur
    method_validate_request
